// Mocks generated by Mockito 5.4.6 from annotations
// in bgmate_flutter/test/presentation/rule_judge/rule_judge_notifier_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:bgmate_flutter/domain/model/judge_history.dart' as _i4;
import 'package:bgmate_flutter/domain/repository/rule_judge_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [RuleJudgeRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockRuleJudgeRepository extends _i1.Mock
    implements _i2.RuleJudgeRepository {
  MockRuleJudgeRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<String> judge(String? gameName, String? question) =>
      (super.noSuchMethod(
            Invocation.method(#judge, [gameName, question]),
            returnValue: _i3.Stream<String>.empty(),
          )
          as _i3.Stream<String>);

  @override
  _i3.Future<void> saveHistory(
    String? gameName,
    String? question,
    String? answer,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#saveHistory, [gameName, question, answer]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Stream<List<_i4.JudgeHistory>> watchHistory(int? limit) =>
      (super.noSuchMethod(
            Invocation.method(#watchHistory, [limit]),
            returnValue: _i3.Stream<List<_i4.JudgeHistory>>.empty(),
          )
          as _i3.Stream<List<_i4.JudgeHistory>>);
}
