// Mocks generated by Mockito 5.4.6 from annotations
// in bgmate_flutter/test/data/repository/recommend_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:bgmate_flutter/data/remote/ai/llm_client.dart' as _i2;
import 'package:bgmate_flutter/data/remote/ai/llm_request.dart' as _i5;
import 'package:bgmate_flutter/data/remote/ai/llm_response.dart' as _i4;
import 'package:bgmate_flutter/domain/model/board_game.dart' as _i8;
import 'package:bgmate_flutter/domain/repository/game_repository.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [LlmClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockLlmClient extends _i1.Mock implements _i2.LlmClient {
  MockLlmClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.LlmResponse> complete(_i5.LlmRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#complete, [request]),
            returnValue: _i3.Future<_i4.LlmResponse>.value(
              _i6.dummyValue<_i4.LlmResponse>(
                this,
                Invocation.method(#complete, [request]),
              ),
            ),
          )
          as _i3.Future<_i4.LlmResponse>);

  @override
  _i3.Stream<String> stream(_i5.LlmRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#stream, [request]),
            returnValue: _i3.Stream<String>.empty(),
          )
          as _i3.Stream<String>);
}

/// A class which mocks [GameRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockGameRepository extends _i1.Mock implements _i7.GameRepository {
  MockGameRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i8.BoardGame>> getCollection() =>
      (super.noSuchMethod(
            Invocation.method(#getCollection, []),
            returnValue: _i3.Future<List<_i8.BoardGame>>.value(
              <_i8.BoardGame>[],
            ),
          )
          as _i3.Future<List<_i8.BoardGame>>);

  @override
  _i3.Stream<List<_i8.BoardGame>> watchGames() =>
      (super.noSuchMethod(
            Invocation.method(#watchGames, []),
            returnValue: _i3.Stream<List<_i8.BoardGame>>.empty(),
          )
          as _i3.Stream<List<_i8.BoardGame>>);

  @override
  _i3.Future<List<_i8.BoardGame>> searchBgg(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchBgg, [query]),
            returnValue: _i3.Future<List<_i8.BoardGame>>.value(
              <_i8.BoardGame>[],
            ),
          )
          as _i3.Future<List<_i8.BoardGame>>);

  @override
  _i3.Future<List<_i8.BoardGame>> enrichWithDetails(
    List<_i8.BoardGame>? games,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#enrichWithDetails, [games]),
            returnValue: _i3.Future<List<_i8.BoardGame>>.value(
              <_i8.BoardGame>[],
            ),
          )
          as _i3.Future<List<_i8.BoardGame>>);

  @override
  _i3.Future<_i8.BoardGame?> getGame(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getGame, [id]),
            returnValue: _i3.Future<_i8.BoardGame?>.value(),
          )
          as _i3.Future<_i8.BoardGame?>);

  @override
  _i3.Future<void> addToCollection(_i8.BoardGame? game) =>
      (super.noSuchMethod(
            Invocation.method(#addToCollection, [game]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> removeFromCollection(_i8.BoardGame? game) =>
      (super.noSuchMethod(
            Invocation.method(#removeFromCollection, [game]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
