// Mocks generated by Mockito 5.4.6 from annotations
// in bgmate_flutter/test/data/service/collection_sync_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:bgmate_flutter/data/remote/bgg_api_service.dart' as _i2;
import 'package:bgmate_flutter/domain/model/bgg_account.dart' as _i8;
import 'package:bgmate_flutter/domain/model/board_game.dart' as _i6;
import 'package:bgmate_flutter/domain/repository/account_repository.dart'
    as _i7;
import 'package:bgmate_flutter/domain/repository/game_repository.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [BggApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockBggApiService extends _i1.Mock implements _i2.BggApiService {
  MockBggApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<String> fetchCollection(
    String? username, {
    int? maxRetries = 5,
    Duration? retryDelay = const Duration(seconds: 3),
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #fetchCollection,
              [username],
              {#maxRetries: maxRetries, #retryDelay: retryDelay},
            ),
            returnValue: _i3.Future<String>.value(
              _i4.dummyValue<String>(
                this,
                Invocation.method(
                  #fetchCollection,
                  [username],
                  {#maxRetries: maxRetries, #retryDelay: retryDelay},
                ),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<String> fetchThingDetails(List<int>? ids) =>
      (super.noSuchMethod(
            Invocation.method(#fetchThingDetails, [ids]),
            returnValue: _i3.Future<String>.value(
              _i4.dummyValue<String>(
                this,
                Invocation.method(#fetchThingDetails, [ids]),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<String> searchGames(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchGames, [query]),
            returnValue: _i3.Future<String>.value(
              _i4.dummyValue<String>(
                this,
                Invocation.method(#searchGames, [query]),
              ),
            ),
          )
          as _i3.Future<String>);
}

/// A class which mocks [GameRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockGameRepository extends _i1.Mock implements _i5.GameRepository {
  MockGameRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i6.BoardGame>> getCollection() =>
      (super.noSuchMethod(
            Invocation.method(#getCollection, []),
            returnValue: _i3.Future<List<_i6.BoardGame>>.value(
              <_i6.BoardGame>[],
            ),
          )
          as _i3.Future<List<_i6.BoardGame>>);

  @override
  _i3.Stream<List<_i6.BoardGame>> watchGames() =>
      (super.noSuchMethod(
            Invocation.method(#watchGames, []),
            returnValue: _i3.Stream<List<_i6.BoardGame>>.empty(),
          )
          as _i3.Stream<List<_i6.BoardGame>>);

  @override
  _i3.Future<List<_i6.BoardGame>> searchBgg(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchBgg, [query]),
            returnValue: _i3.Future<List<_i6.BoardGame>>.value(
              <_i6.BoardGame>[],
            ),
          )
          as _i3.Future<List<_i6.BoardGame>>);

  @override
  _i3.Future<List<_i6.BoardGame>> enrichWithDetails(
    List<_i6.BoardGame>? games,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#enrichWithDetails, [games]),
            returnValue: _i3.Future<List<_i6.BoardGame>>.value(
              <_i6.BoardGame>[],
            ),
          )
          as _i3.Future<List<_i6.BoardGame>>);

  @override
  _i3.Future<_i6.BoardGame?> getGame(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getGame, [id]),
            returnValue: _i3.Future<_i6.BoardGame?>.value(),
          )
          as _i3.Future<_i6.BoardGame?>);

  @override
  _i3.Future<void> addToCollection(_i6.BoardGame? game) =>
      (super.noSuchMethod(
            Invocation.method(#addToCollection, [game]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateGame(_i6.BoardGame? game) =>
      (super.noSuchMethod(
            Invocation.method(#updateGame, [game]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> removeFromCollection(_i6.BoardGame? game) =>
      (super.noSuchMethod(
            Invocation.method(#removeFromCollection, [game]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> upsertGames(List<_i6.BoardGame>? games) =>
      (super.noSuchMethod(
            Invocation.method(#upsertGames, [games]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> removeSyncedGames() =>
      (super.noSuchMethod(
            Invocation.method(#removeSyncedGames, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [AccountRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAccountRepository extends _i1.Mock implements _i7.AccountRepository {
  MockAccountRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i8.BggAccount?> getAccount() =>
      (super.noSuchMethod(
            Invocation.method(#getAccount, []),
            returnValue: _i3.Future<_i8.BggAccount?>.value(),
          )
          as _i3.Future<_i8.BggAccount?>);

  @override
  _i3.Future<void> linkAccount(String? username) =>
      (super.noSuchMethod(
            Invocation.method(#linkAccount, [username]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateLastSyncedAt(DateTime? syncedAt) =>
      (super.noSuchMethod(
            Invocation.method(#updateLastSyncedAt, [syncedAt]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> unlinkAccount() =>
      (super.noSuchMethod(
            Invocation.method(#unlinkAccount, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
